name: mim-gpu
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn=0.23
  - pytest
  - freezegun
  - jupyterlab
  - ipython
  - pip
  - keras
  - autopep8
  - flake8
  - seaborn
  - pip:
    - wfdb
    - tensorflow>=2.3
    - tensorflow_datasets
