name: mim-gpu
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytest
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - freezegun
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator 
  - ipython
  - ipyparallel
  - pip
  - autopep8
  - flake8
  - seaborn
  - graphviz
  - pydot
  - wfdb
  - pre-commit
  - xgboost
  - lxml
  - h5py
  - conda-lock
  - tensorflow-gpu=2.14
  - pytorch-gpu
  - pip:
    - ecg_plot
    - compress_pickle
    - silence-tensorflow
    - torchviz
    - pytorch-symbolic
    - pytorch-model-summary
channel_priority: disabled
