name: mim
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn=0.23
  - pytest
  - freezegun
  - jupyterlab
  - jupyter_contrib_nbextensions
  - ipython
  - pip
  - autopep8
  - flake8
  - seaborn
  - tensorflow>=2.3
  - pip:
    - wfdb
    - tensorflow_datasets

