name: mim
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - pytest
  - freezegun
  - jupyterlab
  - ipython
  - ipyparallel
  - pip
  - autopep8
  - flake8
  - seaborn
  - tensorflow-gpu=2.4.1
  - graphviz
  - pydot
  - wfdb
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pre-commit
  - pip:
    - ecg_plot
    - silence_tensorflow
