name: mim-cpu
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - pytest
  - freezegun
  - jupyterlab
  - ipython
  - ipyparallel
  - pip
  - autopep8
  - flake8
  - seaborn
  - tensorflow >= 2
  - graphviz
  - pydot
  - wfdb
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator 
  - pip:
    - ecg_plot
    - silence_tensorflow
