name: mim-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytest
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - freezegun
  - jupyterlab
  - jupyter_contrib_nbextensions
  - ipython
  - ipyparallel
  - pip
  - autopep8
  - flake8
  - seaborn
  - graphviz
  - pydot
  - wfdb
  - pre-commit
  - xgboost
  - lxml
  - h5py
  - conda-lock
  - tensorflow-gpu=2.12
  - pip:
    - ecg_plot
    - compress-pickle
    - silence-tensorflow
