name: mim-gpu
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn=0.23
  - pytest
  - freezegun
  - jupyterlab
  - ipython
  - pip
  - keras
  - autopep8
  - pip:
    - wfdb
    - tensorflow-gpu==2.3.1