name: mim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytest
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - freezegun
  - jupyterlab
  - ipython
  - ipyparallel
  - pip
  - autopep8
  - flake8
  - seaborn
  - graphviz
  - pydot
  - wfdb
  - pre-commit
  - xgboost
  - tensorflow=2.11
  - pip:
    - ecg_plot
    - compress-pickle
    - silence-tensorflow
