name: mim-cpu
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - scikit-learn=0.23
  - pytest
  - freezegun
  - jupyterlab
  - ipython
  - pip
  - autopep8
  - flake8
  - seaborn
  - pip:
    - wfdb
    - tensorflow >= 2.3.0
    - tensorflow_datasets
    - jupyter_contrib_nbextensions
